"""initial schema

Revision ID: 3fe42f82a56b
Revises: 
Create Date: 2026-04-14 18:17:31.059899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3fe42f82a56b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('lawa_access_token', sa.Text(), nullable=True),
    sa.Column('lawa_refresh_token', sa.Text(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('access_logs',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_logs_created_at'), 'access_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_access_logs_user_id'), 'access_logs', ['user_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('owner_id', app.models.UUID(), nullable=False),
    sa.Column('invite_token', sa.String(length=64), nullable=True),
    sa.Column('invite_token_enabled', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invite_token')
    )
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.create_table('activity_events',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('workspace_id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=True),
    sa.Column('entity_id', app.models.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_events_workspace_id'), 'activity_events', ['workspace_id'], unique=False)
    op.create_table('collections',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('workspace_id', app.models.UUID(), nullable=True),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_user_id'), 'collections', ['user_id'], unique=False)
    op.create_index(op.f('ix_collections_workspace_id'), 'collections', ['workspace_id'], unique=False)
    op.create_table('scouts',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('topic', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('workspace_id', app.models.UUID(), nullable=True),
    sa.Column('include_sources', sa.Text(), nullable=True),
    sa.Column('exclude_sources', sa.Text(), nullable=True),
    sa.Column('schedule_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('email_report', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scouts_user_id'), 'scouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_scouts_workspace_id'), 'scouts', ['workspace_id'], unique=False)
    op.create_table('workspace_invitations',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('workspace_id', app.models.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by', app.models.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_invitations_email'), 'workspace_invitations', ['email'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_token'), 'workspace_invitations', ['token'], unique=True)
    op.create_index(op.f('ix_workspace_invitations_workspace_id'), 'workspace_invitations', ['workspace_id'], unique=False)
    op.create_table('workspace_invite_links',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('workspace_id', app.models.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by', app.models.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_invite_links_token'), 'workspace_invite_links', ['token'], unique=True)
    op.create_index(op.f('ix_workspace_invite_links_workspace_id'), 'workspace_invite_links', ['workspace_id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('workspace_id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('scout_id', app.models.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('findings', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('share_token', sa.String(length=24), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['scout_id'], ['scouts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_scout_id'), 'reports', ['scout_id'], unique=False)
    op.create_index(op.f('ix_reports_share_token'), 'reports', ['share_token'], unique=True)
    op.create_table('collection_items',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('collection_id', app.models.UUID(), nullable=False),
    sa.Column('report_id', app.models.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_report_id'), 'collection_items', ['report_id'], unique=False)
    op.create_table('report_comments',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('report_id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('parent_id', app.models.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['report_comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_comments_parent_id'), 'report_comments', ['parent_id'], unique=False)
    op.create_index(op.f('ix_report_comments_report_id'), 'report_comments', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_comments_user_id'), 'report_comments', ['user_id'], unique=False)
    op.create_table('report_highlights',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('report_id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('selected_text', sa.Text(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_highlights_report_id'), 'report_highlights', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_highlights_user_id'), 'report_highlights', ['user_id'], unique=False)
    op.create_table('report_reactions',
    sa.Column('id', app.models.UUID(), nullable=False),
    sa.Column('report_id', app.models.UUID(), nullable=False),
    sa.Column('user_id', app.models.UUID(), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'user_id', 'emoji', name='uq_report_user_emoji')
    )
    op.create_index(op.f('ix_report_reactions_report_id'), 'report_reactions', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_reactions_user_id'), 'report_reactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_report_reactions_user_id'), table_name='report_reactions')
    op.drop_index(op.f('ix_report_reactions_report_id'), table_name='report_reactions')
    op.drop_table('report_reactions')
    op.drop_index(op.f('ix_report_highlights_user_id'), table_name='report_highlights')
    op.drop_index(op.f('ix_report_highlights_report_id'), table_name='report_highlights')
    op.drop_table('report_highlights')
    op.drop_index(op.f('ix_report_comments_user_id'), table_name='report_comments')
    op.drop_index(op.f('ix_report_comments_report_id'), table_name='report_comments')
    op.drop_index(op.f('ix_report_comments_parent_id'), table_name='report_comments')
    op.drop_table('report_comments')
    op.drop_index(op.f('ix_collection_items_report_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_reports_share_token'), table_name='reports')
    op.drop_index(op.f('ix_reports_scout_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspace_invite_links_workspace_id'), table_name='workspace_invite_links')
    op.drop_index(op.f('ix_workspace_invite_links_token'), table_name='workspace_invite_links')
    op.drop_table('workspace_invite_links')
    op.drop_index(op.f('ix_workspace_invitations_workspace_id'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_token'), table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_email'), table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    op.drop_index(op.f('ix_scouts_workspace_id'), table_name='scouts')
    op.drop_index(op.f('ix_scouts_user_id'), table_name='scouts')
    op.drop_table('scouts')
    op.drop_index(op.f('ix_collections_workspace_id'), table_name='collections')
    op.drop_index(op.f('ix_collections_user_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_activity_events_workspace_id'), table_name='activity_events')
    op.drop_table('activity_events')
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_access_logs_user_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_created_at'), table_name='access_logs')
    op.drop_table('access_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
